### ISSUE TITLE
WAIL exits with harfbuzz version too old

### ISSUE THREAD

**Issue by ctag** [N0taN3rd/wail#106]
### Are you submitting a **bug report** or a **feature request**?

Bug Report, kinda.

### What is the current behavior?

Starting WAIL leads to an error and exit.

### What is the expected behavior?
That it runs.

### What's your environment?

WAIL 1.2.0-beta3.5
Archlinux x64 linux kernel 5.3.5

### Other information

```
$ ./WAIL 

(WAIL:1829738): Pango-ERROR **: 19:34:18.555: Harfbuzz version too old (1.4.2)

$
```

**Comment by ctag** [comment]
If I downgrade pango, then WAIL will run but saving a page gives and error.

[Downgrading pango](https://screeps.com/forum/topic/2797/client-crashes-on-keyboard-input-linux/7):
```
sudo pacman -U https://archive.archlinux.org/packages/p/pango/pango-1%3A1.44.1-1-x86_64.pkg.tar.xz
```

Error:
![2019-10-17_20-03](https://user-images.githubusercontent.com/6200085/67151654-bc4dbd80-f28e-11e9-8795-1b99ff749bfa.png)

Text from error (copied-pasted window above into text editor):

> uncaughtException
> 
> Error: kill ESRCH Error: kill ESRCH
>     at exports._errnoException (util.js:1024:11)
>     at process.kill (internal/process.js:183:13)
>     at /home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:45358:19
>     at /home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:45492:7
>     at Stream.a.end (/home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:45617:5)
>     at Stream.onend (internal/streams/legacy.js:44:10)
>     at emitNone (events.js:110:20)
>     at Stream.emit (events.js:207:7)
>     at end (/home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:46051:39)
>     at Stream.stream.end (/home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:46057:5)
>     at Stream.onend (internal/streams/legacy.js:44:10)
>     at emitNone (events.js:110:20)
>     at Stream.emit (events.js:207:7)
>     at drain (/home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:6462:23)
>     at Stream.stream.queue.stream.push (/home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:6473:5)
>     at Stream.<anonymous> (/home/berocs/downloads/WAIL-linux-x64/resources/app/dist/ui-main.js:46155:10)

That error text looks unrelated to the harfbuzz/pango issue, but I'm including it here.
