### ISSUE TITLE
"No Collection Named:" error

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#80]
I installed version 1.1.0beta2 from the DMG into /Applications, launched, created a collection, then quit. I then deleted the two WAIL folders in ~/Documents and wail-settings waillogs directories in ~/Application_Support/.

When restarting WAIL, I get the interface attached stating there is no collection name (blank).
![screen shot 2017-05-16 at 3 17 14 pm](https://cloud.githubusercontent.com/assets/2514780/26124031/04153714-3a4b-11e7-8acc-b1f2112d64e1.png)

**Comment by machawk1** [comment]
Console 💯:
<details>
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:128582 checkUrl Reducer Object
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:128633 in collections reducer Object
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:128747 runs reducer Object
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:113811 twitter user not signed in
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:125305 no need to display the initial notification event
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:128633 in collections reducer Object
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:128640 Uncaught TypeError: cols.forEach is not a function
    at collectionReducer (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/wail-ui/reducers/collectionReducer.js:20:12)
    at /Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-ignore/lib/index.js:26:1
    at /Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-immutable/dist/combineReducers.js:39:1
    at Array.forEach (native)
    at /Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-immutable/dist/combineReducers.js:36:1
    at Map.withMutations (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/immutable/dist/immutable.js:1355:1)
    at /Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-immutable/dist/combineReducers.js:35:1
    at batchingReducer (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-batched-actions/lib/index.js:21:1)
    at dispatch (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux/es/createStore.js:166:1)
    at /Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-electron-ipc/dist/electron-redux-ipc.js:100:1
    at heritrixRequestHandler (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/wail-ui/middleware/heritrixRequestHandler.js:181:12)
    at action (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/wail-ui/middleware/requestHandler.js:21:14)
    at /Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-promise/lib/index.js:21:1
    at /Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-thunk/lib/index.js:14:1
    at dispatch (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux/es/applyMiddleware.js:35:1)
    at EventEmitter.<anonymous> (/Applications/WAIL.app/Contents/Resources/app/dist/webpack:/~/redux-electron-ipc/dist/electron-redux-ipc.js:90:1)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
/Applications/WAIL.app/Contents/Resources/app/dist/wail.bundle.js:128747 runs reducer Object
</details>

**Comment by N0taN3rd** [comment]
@machawk1 looking into this. 
Thanks for the console output

**Comment by N0taN3rd** [comment]
@machawk1 I have added the fix and created a new [release](https://github.com/N0taN3rd/wail/releases)
Believe a copy paste error occurred as the UI portion of WAIL was expecting an array whereas it was receiving an object. 
The portion of the [archiveManager.js](https://github.com/N0taN3rd/wail/blob/wail-electron/wail-core/managers/archiveManager.js#L255) responsible for the existence of the default collection 
was returning the default collection as an object not wrapped in an array.
